<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9f0897ed-9fa1-4d72-ac34-4800f3caac58</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FileSignatures" Version="7.2.1" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.NetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="IdGen" Version="3.0.7" />
    <PackageReference Include="MaxMind.GeoIP2" Version="5.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.2" />
    <PackageReference Include="Shippo" Version="4.0.2" />
    <PackageReference Include="Stripe.net" Version="51.1.0" />
  </ItemGroup>

</Project>
