POST https://localhost:7039/api/products/variants/images
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="Product_Id"

24305932607422464
--MyBoundary
Content-Disposition: form-data; name="Variant_Id"

24308028295610368
--MyBoundary
Content-Disposition: form-data; name="Images[0].File"; filename="OIP.png"
Content-Type: image/png

< C:\Users\omair\OIP.Png
--MyBoundary
Content-Disposition: form-data; name="Images[0].SortOrder"

1
--MyBoundary
Content-Disposition: form-data; name="Images[1].File"; filename="OIP.png"
Content-Type: image/png

< C:\Users\omair\OIP.Png
--MyBoundary
Content-Disposition: form-data; name="Images[1].SortOrder"

3
--MyBoundary--

### login
POST https://localhost:7039/auth/login
Content-Type: application/json
{
    "username": "omi@gmail.com",
    "password": "1234"
}
