<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>7f342e59-c0e1-4ef5-9bd1-126a96fa7a5b</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <Content Update="appsettings.Development.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.6" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.4" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\Helpers\" />
      <Folder Include="Controllers\Categories\" />
      <Folder Include="Controllers\Orders\" />
      <Folder Include="Controllers\Products\Responses\" />
      <Folder Include="Controllers\Users\" />
      <Folder Include="wwwroot\uploads\products\images\" />
      <Folder Include="wwwroot\uploads\products\images\original\" />
      <Folder Include="wwwroot\uploads\products\reporsts\" />
    </ItemGroup>
    
    <PropertyGroup>
        <!--<PublishAot>true</PublishAot>

        <TrimMode>full</TrimMode>

        <StackTraceSupport>false</StackTraceSupport>-->
        <InvariantGlobalization>false</InvariantGlobalization>
        <OptimizationPreference>Size</OptimizationPreference>
        <ServerGarbageCollection>false</ServerGarbageCollection>
    </PropertyGroup>
</Project>
